version: '3.1'

services:
  api:
    build: .
    depends_on:
      - database
    links:
      - database
    ports:
      - 8081:8081

  database:
    image: postgres:13.1
    env_file:
      - postgres.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080