version: '3.1'

services:
  # TODO: api image

  database:
    image: postgres:13.1
    env_file:
      - postgres.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8081