server:
  port = 8081

spring:
  datasource:
    url = jdbc:postgresql://database:5432/todolist
    username = todoUser
    password = todoListPass

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update